### PR TITLE
Removed check for zero transfer. Fixes #47.

### LINKED ISSUE #47: Make 0-valued transfers valid semantics (fire the event and return true)
EDIT:  Replace "revert" with "returned false" in this issue; I realized StandardToken does not throw on error but then realized the issue is practically the same and still just as harmful

Reverting on 0-valued transfer and approval is an anti-pattern that pops up repeatedly in code reviews. I realized it's because many people are copying your StandardToken. 

These two lines should have `&& _value > 0` removed:
```
        if (balances[msg.sender] >= _value && _value > 0) {
```

```
        if (balances[_from] >= _value && allowed[_from][msg.sender] >= _value && _value > 0) {
```

0-valued transfers and approvals should be valid and behave almost like no-ops, without reverting state. This is so that consumer contracts do not have to take care to work around this edge case.

### PR DESCRIPTION
**Pull request by simondlr**

### CODE REVIEW

**Comment by simondlr** [comment]
@ethers if you want to review. :)

**Comment by ethers** [comment]
There should also be a test for ensuring that true is returned and correct event is fired...

**Comment by simondlr** [comment]
Cool. Yes.

**Comment by simondlr** [comment]
@skmgoldin if you have time and continuing with tidying up this codebase, can you add a test for this as well, so we can finally merge this in?

**Comment by skmgoldin** [comment]
Yes will do @simondlr.

**Comment by skmgoldin** [comment]
I rebased this on master so it's mergeable, gonna do a force push.

**Comment by skmgoldin** [comment]
I vote we merge this and then address #15 separately.

**Comment by GNSPS** [comment]
My vote is 👍 given there still are no test accounting for correct event firing that can be a totally independent PR.

💯 for all the hard work at this @skmgoldin !

**Pull request merged**
