### PR TITLE
Added some functions for functions that are supported in Mist by default

### PR DESCRIPTION
**Pull request by alexvandesande**
These are functions we would like to push for the next stable token standard proposal

### CODE REVIEW

**Comment by simondlr** [comment]
Is there any explanation on this or an ERC?

I know of the call action (I saw it in the Unicorn code). Need to give some thought on this functionality. Can you elaborate on this and why it is needed?

As for the symbols/decimals/etc. Wasn't it determined that this is the responsibility of a registry and/or the front-end to add additional context? Not all tokens will worry/bother with decimals/symbols/name.

**Comment by alexvandesande** [comment]
@simondlr There was a discussion on this on the Token Standard ERC, but it was lost after all the threads. I can start a token standard ERC 2.0 discussion. The ApproveAndCall action reduces the amount of steps the user needs to take when sending tokens to a contract. Right now they have to first execute a transaction to approve, then they must make a transaction to the contract to notice that they've approved them, so the contract can act on it. With ApproveAndCall there's only one step.

About the display information, they are optional, but I strongly suggest users to. It's already implemented on the Ethereum Wallet and it reduces the amount of work the user needs to do, and I haven't seen anyone working on token registries yet.

**Comment by simondlr** [comment]
I see.

It makes more sense that is an optional function, rather it being the only way to approve, since you will then essentially force the user to pay additional gas costs each time with no gain (calling with no use). How do you choose which one to use in an interface? If all approve()'s default to approveAndCall() isn't that detrimental to the user? ie, if I'm approving a friend (there's no contract there), wouldn't this cause needless gas to be consumed?

I have thought of ways to make this easier, and I haven't found an optimal way. It seems that it is potentially sub-optimal. From a UX perspective, it makes sense to have the call in there is well. Like you said. It is less effort and reduces steps.

Another scenario would be to keep it as is and rely on dapp-specific UI cues to reduce UX overhead. For example, let's assume a contract needs to be notified. When on the dapp-page, it will know what address is the user's and can do an eth.call() to display to the user as IF this "check" has already been done. For example, I approve() EtherEx to use 30 of my tokens. When I'm on EtherEx, it shows that I have actually "deposited" my tokens, even though on the contract level, in EtherEx's case, nothing has happened. When an order is put up, only then does it potentially withdraw the tokens and put it into contract escrow (or something). So from a user's perspective, it all looks as if EtherEx was notified at a contract level, whilst it hasn't yet.

It is not foolproof however if the user's approval() changes how other users' dapp experience behaves. For example, if I approve() some of my tokens for a pool of collateral, at the contract level, it needs to be updated, considering multiple users' tokens might be put up as collateral. 

So, I suspect it could be very dapp-specific behaviour to notify a contract of an approval. Thus, I'm wary, in terms of separating concerns to force certain behaviour. I do agree it is a good optional behaviour.

I do also think that adding in symbols, names & decimals seems like good optionals. I don't necessarily want this standard token to reflect human-based tokens only, so I don't think it should be in the "standard". We could perhaps make like a new ERC extension for "human" tokens?

The initial total supply is also an optional thing that I'm forcing to be a part of the standard token, which it probably shouldn't be. I'm going to try and morph this around a bit to indicate what's optional and what's core. And then go back to creating differents version that have different optionals attached (explaining reason & use).

ie: Optional 1: Initial Finite Supply, approveAndCall, human-readable fields, etc.

What do you think?

**Comment by alexvandesande** [comment]
I started this path thinking that all approve calls should also have a call inside it, but I was convinced by similar discussions, which is why approveAndCall is a separate function. 

I agree on leaving all those as optionals, the reason I made this PR here is because I noticed some users of our wallet were using this code to build their tokens, without giving it much thought so I think it's nice to include all the nicer options by default.

**Comment by simondlr** [comment]
Ah yes. Okay. That could cause some trouble without the right expectations.
Lemme see how I can shuffle things round a bit. Will report back with some
thoughts!

**Comment by simondlr** [comment]
So, I made substantial reworking and modded stuff a bit. 

Essentially moved StandardToken.sol so that it ONLY implements ERC20 (nothing else).
...and a HumanStandardToken.sol with the optional extras for deployment for humans (with tests).

But suffering from pretty sweet 3rd world intermittent internet. ;)

Will submit a pull request later with some changes, then we can discuss.

**Comment by alexvandesande** [comment]
That's great simon, thanks!

**Comment by ethers** [comment]
@alexvandesande How about `metadata` being generic, and Mist can define a standard based on it?  https://github.com/ConsenSys/Tokens/pull/12/files#r63259807

**Comment by simondlr** [comment]
Thanks for the code additions @alexvandesande! Merged the other pull request.

**Pull request closed without merging**
