### PR TITLE
Standard structure

### PR DESCRIPTION
**Pull request by maurelian**
I think this is a more common structure for simple truffle projects. 

Not sure why there's an "x", I see no conflicts.

### CODE REVIEW

**Comment by simondlr** [comment]
Yes. This is vestigial when the Tokens repo still had the Token Factory pulled in.

It seems package lock also got committed?

**Comment by maurelian** [comment]
Re: package-lock: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

It shouldn't interfere with anyone using npm@^4.x.x as package.json is still there.

Regarding merge conflicts, I'm not sure what that was about, but I fixed it by merging upstream master into this branch.

**Comment by simondlr** [comment]
Cool. LGTM. Merging.

**Comment by simondlr** [comment]
The codeship is failing after this merge. I assume it's because of the changed folder structure. cc @skmgoldin?

**Comment by skmgoldin** [comment]
This is why we merge to staging first. ;) I'll take a look.

**Comment by skmgoldin** [comment]
Yup, it was the folder structure. Fixed now.

**Comment by simondlr** [comment]
Thanks @skmgoldin!

**Pull request merged**
