### PR TITLE
Add unlimited allowance to StandardToken

### PR DESCRIPTION
**Pull request by abandeali1**
See https://github.com/ethereum/EIPs/issues/717 for a full explanation.

### CODE REVIEW

**Comment by maurelian** [comment]
Thanks @abandeali1 this looks good to me. Will try to get it reviewed quickly.

**Comment by simondlr** [comment]
I'm happy with adding this. Unless there's anything else we should take a look at, we can merge into staging to see if the tests pass okay.

**Comment by maurelian** [comment]
OK, I'll run the tests, and review that additional test.

**Comment by maurelian** [comment]
@abandeali1 your new test appears to be failing, it's not clear to me why, but the allowance is being reduced. 

In order to get better console output, I changed line 193 of the test file to 

    assert.equal(allowance01.toString(), max);

This give me: 
```
AssertionError: expected '1.15792089237316195423570985008687907853269984665640564039457584007913129639915e+77' to equal '1.15792089237316195423570985008687907853269984665640564039457584007913129639935e+77'
```

notice the ..15e+77, vs. 35e+77. 

It seems the amount is being decremented, and I'm not sure why. Is the test passing for you?

**Comment by abandeali1** [comment]
Hmm, the tests all pass when I run them locally (on branch `staging` after the merge). I am using truffle v3.4.9 and testrpc v4.1.3.

**Comment by maurelian** [comment]
I'm on same testrpc version.
I'm was using truffle 4, but downgraded to 3.4.9 with the same result. I'm a bit baffled right now.

**Comment by maurelian** [comment]
I got it working.

**Pull request merged**
