### PR TITLE
Rewrite tests with async/await

### PR DESCRIPTION
**Pull request by Janaka-Steph**
Hello,

This is the tests using async/await, plus a little helper to test throwing. 
They are passing.

Let me know what do you think

### CODE REVIEW

**Comment by actum88** [comment]
Dear All, 

 We need with the greatest urgency a good smart contract that contemplates the prerogatives we need.
I checked a ICO's that I liked very much about the smart contract. as for BlockCat (CAT) I could take a look at the smart contract, which for the crowdsale followed the 1St Blood token. I liked too.

So, would somebody be possible in the next week to create a smart contract for us with the following characteristics? Check them below:

1 - 600 million tokens

2 - 18 decimals

3 - Simbol: NBC

4 - 3 months of ICO

5 - 300 million for pre-sale and sale in ICO, which is not sold in the first 3 months, should be destroyed (burned);

6 - 50 million for division between 10 founders (5 million for each);

7 - 250 million for the future business of the team, that is, will be in the name of the account of the creator, who will be one of the 10 founders, and will only enter into circulation with the implementation of the business that NBC will fund (still in secrecy)

8 - a) First and Second Weeks 1 ETH = 300 NBC

B) Third and Four Weeks 1 ETH = 275 NBC

C) Fifth and Sixth Weeks 1 ETH = 250 NBC

D) Seventh and Eighth Weeks 1 ETH = 225 NBC

E) Ninth week until the end of the third month 1 ETH = 200 NBC

F) We want to accept Bitcons too, which should be parameterized. Can we have others also like XRP or Monero?

9 - At each NBC is sald, each of the 10 founders shall receive 2.5% of the amounts, that is, 25% of the total sales;

10 - The 75% of the sale should go to the account of the creator, that is, to the account that will finance the mentioned business, which will be kept secret until the launch of the business.


Tese are our needs and if you have any other ideas that can complement, we accept suggestions.

Can you create the smart contract and at what price? We'll also need a consultancy to make the deployment error-free. Send us the price too.

Then we could continue with the work for the implantation of ICO in a second stage with more calm.

Regards,

Fernando Barrueco
cel. +55-11-98326-0077


Enviado do meu iPhone

**Comment by simondlr** [comment]
Deleted the spam comment asking for development for an ICO. Absolutely not the place for this.

**Comment by skmgoldin** [comment]
Hey @Janaka-Steph could you make this PR to the staging branch? Sorry, I need to add that to the README.

**Comment by Janaka-Steph** [comment]
Done https://github.com/ConsenSys/Tokens/pull/71
Sorry I screwed up a bit when rebasing the staging branch, it has duplicated the commit I don't know why, but the content of the PR is the same, should be ok.

**Pull request closed without merging**
