### PR TITLE
Add tests for events. Fixes #15.

### LINKED ISSUE #15: Need tests for events

### PR DESCRIPTION
**Pull request by skmgoldin**
Adds tests for the Transfer and Approval events to `humanStandardToken.js`. Addresses #15.

### CODE REVIEW

**Comment by simondlr** [comment]
Thanks @skmgoldin! 

Do we know what the final consensus was on the events that should be fired in the event of transfer zero? Should it fire? cc @ethers

**Comment by skmgoldin** [comment]
Zero transfers are normal transfers, so an event should fire. Do you want me to add a test for it?

**Comment by skmgoldin** [comment]
Did it.

**Comment by simondlr** [comment]
Whoop. Thanks @skmgoldin!

**Pull request merged**
