### PR TITLE
Gitcoin: Solhint linter

### PR DESCRIPTION
**Pull request by Elaniobro**
#### Description
* Added `solhint` version `^1.1.9`
* Did basic linting of `.sol` files
* Combined `lint` command with `eslint`

#### Issues
* #100  

#### Todo
[x] add override config
[x] add badges to `README.md`

### CODE REVIEW

**Comment by Elaniobro** [comment]
Updated with completed todos

**Comment by maurelian** [comment]
Sorry for the delay here. We've made a fairy major update to the code, which is currently on the staging branch. I can take responsibility for linting that new code though, and its good to see that you've been rewarded for the bounty. I'll do my best to ensure you make it into the commit history too.

**Comment by Elaniobro** [comment]
Hey @maurelian I don't see that the bounty went through. Also, this PR still is un-merged. Glad to hear that the linting has helped. Let me know if there is anything else. 

Cheers!

**Comment by maurelian** [comment]
The bounty itself was actually opened by @owocki

I merged your changes with the updated code base here: https://github.com/ConsenSys/Tokens/tree/Elaniobro-Gitcoin-linter, I'd like to update that to eslint with airnbnb before merging it, and some of the badges don't appear to reflect reality..

**Comment by Elaniobro** [comment]
@maurelian there could be rate limit issue(s). Are you able to add the [shields application](https://github.com/login/oauth/authorize?client_id=cceb16b11fcb57269101&redirect_uri=https%3A%2F%2Fimg.shields.io%2Fgithub-auth%2Fdone) to the repo?

**Comment by owocki** [comment]
remitting the bounty now

**Comment by owocki** [comment]
remitted https://github.com/ConsenSys/Tokens/issues/100#issuecomment-353030746

**Comment by maurelian** [comment]
Thanks all!

**Pull request closed without merging**
