### PR TITLE
Version bumps

### PR DESCRIPTION
**Pull request by maurelian**
I've merged #128 into staging. 

Summary of changes: 
* version updates in package.json
* added `emit` on event calls
* added solhint disable comments (solhint doesn't support `emit` yet)

### CODE REVIEW

**Comment by skmgoldin** [comment]
Looks like it's the coverage tool that's failing. I'm still not an expert in how that tool works, @maurelian do you have any idea why it's failing?

**Comment by maurelian** [comment]
It's weird. This is from the CI output: 

```Writing artifacts to ./build/contracts

testRpc stderr:
/bin/sh: 1: ./node_modules/ethereumjs-testrpc-sc/build/cli.node.js: not found

Cleaning up...
testRpc errored after launching as a childprocess.
Exiting without generating coverage...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! erc20-tokens@0.0.1 coverage: `solidity-coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the erc20-tokens@0.0.1 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rof/.npm/_logs/2018-04-12T16_39_47_878Z-debug.log```

But the same command, (`npm run coverage`) works fine on my machine.

**Comment by simondlr** [comment]
> But the same command, (npm run coverage) works fine on my machine.

Same here. My code smell wonders why testrpc is being run vs ganache core? Is that a solidity-coverage dependency? Maybe a dead-end to think about. Hmm

**Comment by simondlr** [comment]
This might fix it: https://github.com/sc-forks/solidity-coverage/pull/215. I'll revert back to this soon, but want to get ERC721 into a WIP sooner before tackling this issue.

**Comment by simondlr** [comment]
Any recommendations on how to proceed? Keep debugging? Try latest version of solcover [with hash commit]? Need to have this merged soon before ERC721 code comes in. :)

**Comment by maurelian** [comment]
Updated solidity-coverage to fix the build.

**Pull request merged**
